Add generic get regex function
erichte-ibm/conga pull request #16
Opened 2021-10-15 20:50 UTC by nick-child-ibm

Dependent on PR #15. I can remove this dependency if it gets held up.

Addresses Issue #4.
This commit adds a function to the `Collector` class for returning a string representation of a regex match when given a command and a regex string. I have demonstrated how this method helps the process of retrieving data by using it in the current data gathering functions.

Let me know if this was not what was intended in the Issue description

2021-10-29 19:22 UTC, erichte-ibm commented on src/collector.rs
> +    pub fn get_regex_from_command(&mut self, command: &str, regex: &str) -> Option<String> {
`parse_from_command`, as it is returning the parsed output, not the regex itself

2021-10-29 19:23 UTC, erichte-ibm commented on src/collector.rs
> +        let output = String::from_utf8(out.stdout).unwrap();
some commands (like `gcc -v`) will output on `stderr`, may want to make this an option, or parse both? probably option?

2021-10-29 19:27 UTC, erichte-ibm commented on src/collector.rs
> +        }
Can we explore this a bit? Perhaps there's an option to let us return the whole cap object here without upsetting the borrow checker, that way we don't have to arbitrarily return only the first.

2021-10-29 19:29 UTC, erichte-ibm commented on src/collector.rs
> +    pub fn get_regex_from_command(&mut self, command: &str, regex: &str) -> Option<String> {
Return a `Result<String, Error>`, so we can use `?` and send the error upwards, or return a value.

2021-10-29 19:31 UTC, erichte-ibm commented on src/collector.rs
> +        let re = Regex::new(regex).unwrap();
This is allowed to panic, our regexes should always at least compile (assuming that's what the possible error is here)

2021-10-29 19:39 UTC, erichte-ibm commented on src/collector.rs
> +        let cap = re.captures(&output).unwrap();
Return either `None` here if keeping return type as `Option<..>`, or return an `Error` here. We should not panic the whole collection process if one collector dies

2021-10-29 19:56 UTC, erichte-ibm requested changes
1. Don't panic on parse changes
2. Try to return full captures if possible
3. stdout vs stderr

2021-12-10 20:34 UTC, nick-child-ibm commented
Made following changes:
-changed function name
-changed return type to Result instead of Option
-now we return a Vector<string> of all matches instead of one string of first match
-add parameter for specifying where to read output from stdout or stderr

2022-02-11 20:11 UTC, erichte-ibm commented on src/collector.rs
> +        }
```
let output = match out_type { 
           OutputStream::STDOUT => String::from_utf8(out.stdout)?,
           OutputStream::STDERR => output = String::from_utf8(out.stderr)?,
}

2022-02-11 20:11 UTC, erichte-ibm commented on src/collector.rs
> +        }
```
return match cap { ... }
```

2022-02-11 20:12 UTC, merged